# Generated by scripts/release.py homebrew; do not edit checksums by hand.
class CodexRetain < Formula
  desc "Predictable local retention for archived Codex chats"
  homepage "https://github.com/Dankosik/codex-retain"
  version "0.1.0"
  license "MIT"

  depends_on macos: :sequoia

  on_macos do
    on_arm do
      url "https://github.com/Dankosik/codex-retain/releases/download/0.1.0/codex-retain-0.1.0-aarch64-apple-darwin.tar.gz"
      sha256 "41a86564e9da85f75249e5527a3b299c84619ddfa85f4079da571ecc52d55469"
    end
    on_intel do
      url "https://github.com/Dankosik/codex-retain/releases/download/0.1.0/codex-retain-0.1.0-x86_64-apple-darwin.tar.gz"
      sha256 "d248afd4fd7b22951df9cd14bb554332b7b25b83e86f61bda3b9f89c68ec6f3b"
    end
  end

  def install
    bin.install "codex-retain"
    generate_completions_from_executable(bin/"codex-retain", "completions")
  end

  def caveats
    <<~EOS
      Installation does not enable retention. Run codex-retain doctor first.
      Enable using codex-retain on PATH so the schedule follows brew upgrades.
      Before brew uninstall, run codex-retain uninstall to remove the schedule.
    EOS
  end

  test do
    ENV["CODEX_HOME"] = testpath/"missing-codex"
    ENV["CODEX_RETAIN_STATE_DIR"] = testpath/"missing-policy"
    assert_equal "codex-retain #{version}\n", shell_output("#{bin}/codex-retain --version")
    assert_match "preview", shell_output("#{bin}/codex-retain --help")
    refute_path_exists testpath/"missing-codex"
    refute_path_exists testpath/"missing-policy"
  end
end
