# Generated by scripts/release.py homebrew; do not edit checksums by hand.
class CodexRetain < Formula
  desc "Predictable local retention for archived Codex chats"
  homepage "https://github.com/Dankosik/codex-retain"
  version "0.1.1"
  license "MIT"

  depends_on macos: :sequoia

  on_macos do
    on_arm do
      url "https://github.com/Dankosik/codex-retain/releases/download/0.1.1/codex-retain-0.1.1-aarch64-apple-darwin.tar.gz"
      sha256 "53938e2387c19ccbc5a30bb8979c11941efa60ea1969dcb30805a36f4e4877e5"
    end
    on_intel do
      url "https://github.com/Dankosik/codex-retain/releases/download/0.1.1/codex-retain-0.1.1-x86_64-apple-darwin.tar.gz"
      sha256 "04b049b77ab90082316e0693ead99e2c024e4b5a12fa314049d8d600dca2cdf9"
    end
  end

  def install
    bin.install "codex-retain"
    generate_completions_from_executable(bin/"codex-retain", "completions")
  end

  def caveats
    <<~EOS
      Installation does not enable retention. Run codex-retain doctor first.
      Enable using codex-retain on PATH so the schedule follows brew upgrades.
      Before brew uninstall, run codex-retain uninstall to remove the schedule.
    EOS
  end

  test do
    ENV["CODEX_HOME"] = testpath/"missing-codex"
    ENV["CODEX_RETAIN_STATE_DIR"] = testpath/"missing-policy"
    assert_equal "codex-retain #{version}\n", shell_output("#{bin}/codex-retain --version")
    assert_match "preview", shell_output("#{bin}/codex-retain --help")
    refute_path_exists testpath/"missing-codex"
    refute_path_exists testpath/"missing-policy"
  end
end
