# Generated by scripts/release.py homebrew; do not edit checksums by hand.
class CodexRetain < Formula
  desc "Predictable local retention for archived Codex chats"
  homepage "https://github.com/Dankosik/codex-retain"
  if Hardware::CPU.arm?
    url "https://github.com/Dankosik/codex-retain/releases/download/0.1.3/codex-retain-0.1.3-aarch64-apple-darwin.tar.gz"
    sha256 "83e798581edbbd3a1bc3022b23e3cf6408cd3daf863da862291aeeceaff53e25"
  else
    url "https://github.com/Dankosik/codex-retain/releases/download/0.1.3/codex-retain-0.1.3-x86_64-apple-darwin.tar.gz"
    sha256 "869ee2ce5fafb14954ef671709c18ca1716bbdd94bc1bb32f844f7ff8c1816dc"
  end
  version "0.1.3"
  license "MIT"

  depends_on macos: :sequoia

  def install
    bin.install "codex-retain"
    generate_completions_from_executable(bin/"codex-retain", "completions")
  end

  def caveats
    <<~EOS
      Installation does not enable retention. Run codex-retain doctor first.
      Enable using codex-retain on PATH so the schedule follows brew upgrades.
      Before brew uninstall, run codex-retain uninstall to remove the schedule.
    EOS
  end

  test do
    ENV["CODEX_HOME"] = testpath/"missing-codex"
    ENV["CODEX_RETAIN_STATE_DIR"] = testpath/"missing-policy"
    assert_equal "codex-retain #{version}\n", shell_output("#{bin}/codex-retain --version")
    assert_match "preview", shell_output("#{bin}/codex-retain --help")
    refute_path_exists testpath/"missing-codex"
    refute_path_exists testpath/"missing-policy"
  end
end
